import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
const bricolage = Bricolage_Grotesque({
    subsets: ["latin"],
    weight: ["400", "700"],
    variable: "--font-bricolage",
  });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function InspirationGalleryLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div
        className={`antialiased ${bricolage.className} bg-[#efede8] md:mt-16 dark:bg-black text-[#1c1c1c] dark:text-white`}
      >
        {children}
      </div>
  );
}
